log:
  # format: json
  level: debug
database:
  sqlite:
    file: zhero.db

admin:
  server:
    port: 8081
  rdf:
    file: "rdf_schema.jsonld"
    source: "https://raw.githubusercontent.com/schemaorg/schemaorg/refs/heads/main/data/releases/29.2/schemaorg-all-https.jsonld"

public:
  server:
    port: 8080
